-- liquibase formatted sql

-- changeset Admin:1751266697101-1
CREATE TABLE ads
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(32)                              NOT NULL,
    price       INTEGER                                  NOT NULL,
    description VARCHAR(64)                              NOT NULL,
    author_id   INTEGER,
    image_id    UUID,
    CONSTRAINT pk_ads PRIMARY KEY (id)
);

-- changeset Admin:1751266697101-2
ALTER TABLE ads
    ADD CONSTRAINT FK_ADS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id);

-- changeset Admin:1751266697101-3
ALTER TABLE ads
    ADD CONSTRAINT FK_ADS_ON_IMAGE FOREIGN KEY (image_id) REFERENCES images (id);

