-- liquibase formatted sql

-- changeset Admin:1751278152322-2
CREATE TABLE comments
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at BIGINT,
    text       VARCHAR(64)                              NOT NULL,
    author_id  INTEGER,
    ad_id      INTEGER,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

-- changeset Admin:1751278152322-3
ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_AD FOREIGN KEY (ad_id) REFERENCES ads (id);

-- changeset Admin:1751278152322-4
ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id);

-- changeset Admin:1751278152322-1
ALTER TABLE ads
    ALTER COLUMN author_id DROP NOT NULL;

